# Generated by Django 2.1.4 on 2019-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190101_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
