# Generated by Django 2.1.4 on 2019-01-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
